{
 "title": "Java Otel Dashboard",
 "tags": [
  "otel",
  "perfana"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "system_under_test",
    "query": {
     "query": "label_values(jvm_cpu_count,system_under_test)"
    }
   },
   {
    "name": "test_environment",
    "query": {
     "query": "label_values(jvm_cpu_count{system_under_test=\"$system_under_test\"},test_environment)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(jvm_cpu_count{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Server response times 95P",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_server_request_duration_seconds_bucket{http_response_status_code=\"200\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", job=\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{http_route}} {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Server incoming rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_count{http_response_status_code=\"200\", system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", job=\"$service\"}[$__rate_interval])",
     "legendFormat": "{{http_route}} {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Server response times 95P errors",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_server_request_duration_seconds_bucket{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", job=\"$service\", http_response_status_code!=\"200\"}[$__rate_interval]))",
     "legendFormat": "{{http_route}} {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Server incoming rate errors",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_count{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", job=\"$service\", http_response_status_code!=\"200\"}[$__rate_interval])",
     "legendFormat": "{{http_route}} {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Client response times 95P",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_client_request_duration_seconds_bucket{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", job=\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{server_address}} {{server_port}} {{error_type}}"
    }
   ]
  },
  {
   "title": "Client outgoing rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_client_request_duration_seconds_count{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", job=\"$service\"}[$__rate_interval])",
     "legendFormat": "{{server_address}} {{server_port}} {{error_type}}"
    }
   ]
  },
  {
   "title": "Database response times 95P",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(db_client_connections_use_time_milliseconds_bucket{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", job=\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "Database outgoing rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(db_client_connections_use_time_milliseconds_count{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", job=\"$service\"}[$__rate_interval])",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "Database pending requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "db_client_connections_pending_requests{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", job=\"$service\"}",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "Database connections usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "db_client_connections_usage{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", job=\"$service\"}",
     "legendFormat": "{{pool_name}} {{state}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", job=\"$service\"}",
     "legendFormat": "{{jvm_memory_type}} {{jvm_memory_pool_name}}"
    }
   ]
  },
  {
   "title": "CPU time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_cpu_time_seconds_total{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", job=\"$service\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_thread_count{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", job=\"$service\"}",
     "legendFormat": "{{jvm_thread_state}} deamon: {{jvm_thread_daemon}}"
    }
   ]
  }
 ]
}