{
 "title": "HTTP connection pool",
 "tags": [
  "http connection pool",
  "perfana",
  "perfana-template"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "system_under_test",
    "query": {
     "query": "label_values(httpcomponents_httpclient_pool_total_connections, system_under_test)"
    }
   },
   {
    "name": "test_environment",
    "query": {
     "query": "label_values(httpcomponents_httpclient_pool_total_connections{system_under_test=\"$system_under_test\"}, test_environment)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(httpcomponents_httpclient_pool_total_connections{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\"},service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP connection pool in use",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(httpcomponents_httpclient_pool_total_connections{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", service=\"$service\", state=\"leased\"}) by(httpclient) / avg(clamp_min(httpcomponents_httpclient_pool_total_max{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", service=\"$service\"}, 1)) by(httpclient) ",
     "legendFormat": "{{httpclient}}"
    }
   ]
  },
  {
   "title": "HTTP connection pool route max default",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg by(httpclient) (httpcomponents_httpclient_pool_route_max_default{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", service=\"$service\"})",
     "legendFormat": "{{httpclient}}"
    }
   ]
  },
  {
   "title": "HTTP connection pool pending",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg by(httpclient) (httpcomponents_httpclient_pool_total_pending{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", service=\"$service\"})",
     "legendFormat": "{{httpclient}}"
    }
   ]
  },
  {
   "title": "HTTP connection pool max",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg by(httpclient) (httpcomponents_httpclient_pool_total_max{system_under_test=\"$system_under_test\", test_environment=\"$test_environment\", service=\"$service\"})",
     "legendFormat": "{{httpclient}}"
    }
   ]
  }
 ]
}