services:
  db:
    image: postgres:latest
    container_name: postgres-tiny-bank
    environment:
      POSTGRES_DB: tiny_bank_db
      POSTGRES_USER: pipo
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  toxiproxy:
    image: shopify/toxiproxy
    container_name: toxiproxy
    ports:
      - "8474:8474"
      - "15432:15432"

volumes:
  postgres-data: