receivers:
  zipkin:
    endpoint: 0.0.0.0:9411
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:
extensions:
  zpages: {}
exporters:
  debug:
    verbosity: detailed
  prometheusremotewrite:
      endpoint: "http://prometheus:9090/api/v1/write"
service:
  telemetry:
    logs:
      level: "DEBUG"
      development: true
      encoding: "json"
  extensions: [zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [debug, prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [debug]
    traces:
      receivers: [otlp, zipkin]
      processors: []
      exporters: [debug]
